import streamlit as st
import pandas as pd

# ==================================================
# VALUE FORMATTING
# ==================================================

def display_value(value):
    """
    Convert dataframe values into readable catalogue text.

    The loader stores multi-value Excel fields as Python lists.
    This function converts them back into a human-readable format
    for display inside the catalogue interface.

    Example:
        ["Italian", "English"]

    becomes:

        Italian; English
    """

    if value is None:
        return ""

    if isinstance(value, list):

        return "; ".join(
            str(item)
            for item in value
        )

    return str(value)


# ==================================================
# CATALOGUE DISPLAY PREPARATION
# ==================================================

def prepare_catalogue_view(df):
    """
    Prepare catalogue data for visualisation.

    The original dataframe is preserved.

    Operations:
    - remove internal search columns
    - convert structured values into readable text

    The returned dataframe is only used by the UI layer.
    """

    catalogue = df.copy()

    # Internal columns generated by the search engine.
    # They are required for ranking but should not appear
    # in the public catalogue view.

    hidden_columns = [
        "_search_text",
        "_isbn_clean",
        "_match_score"
    ]

    for column in hidden_columns:

        if column in catalogue.columns:

            catalogue = catalogue.drop(
                columns=[column]
            )

    # Convert Python lists and special values
    # into readable catalogue strings.

    for column in catalogue.columns:

        catalogue[column] = (
            catalogue[column]
            .apply(display_value)
        )

    return catalogue


# ==================================================
# COMPLETE CATALOGUE PAGE
# ==================================================

def show_catalogue(df):
    """
    Display the complete library catalogue.

    Provides:
    - catalogue statistics
    - interactive dataframe view
    - CSV export functionality
    """

    catalogue = prepare_catalogue_view(df)


    # ----------------------------------------------
    # Catalogue statistics
    # ----------------------------------------------

    col1, col2 = st.columns(2)

    with col1:

        st.metric(
            "Records",
            len(catalogue)
        )

    with col2:

        st.metric(
            "Metadata fields",
            len(catalogue.columns)
        )


    st.divider()


    # ----------------------------------------------
    # Interactive catalogue table
    # ----------------------------------------------
    #
    # Streamlit dataframe provides:
    # - scrolling
    # - column resizing
    # - data exploration

    st.dataframe(
        catalogue,
        use_container_width=True,
        height=700
    )


    # ----------------------------------------------
    # CSV EXPORT
    # ----------------------------------------------
    #
    # Export keeps the cleaned display format
    # instead of exposing internal application fields.

    csv = catalogue.to_csv(
        index=False,
        sep=";"
    )

    st.download_button(
        label="⬇️ Export catalogue CSV",
        data=csv,
        file_name="library_catalogue_export.csv",
        mime="text/csv"
    )