import streamlit as st
import pandas as pd

from modules.config import (
    COLUMNS,
    COLUMN_DESCRIPTIONS
)

# ==================================================
# VALUE TYPE ANALYSIS
# ==================================================

def analyse_value_type(series):
    """
    Detect the dominant data type of a catalogue field.

    Supported types:
    - Text values
    - Numeric values
    - Dates
    - Lists generated by the loader
    - Empty fields

    Used by the metadata dashboard to describe
    the structure of every bibliographic field.
    """

    values = series.dropna().tolist()

    if not values:
        return "Empty"

    # List fields are generated by loader.py
    # when multiple values are stored in one cell.
    if any(isinstance(value, list) for value in values):
        return "List"

    # Numeric fields include years, pages, prices, etc.
    if all(isinstance(value, (int, float)) for value in values):
        return "Numeric"

    # Pandas datetime detection for date fields.
    if pd.api.types.is_datetime64_any_dtype(series):
        return "Date"

    return "Text"


# ==================================================
# METADATA VALUE NORMALIZATION
# ==================================================

def flatten_metadata_value(value):
    """
    Convert catalogue values into comparable elements.

    Multi-value fields stored as Python lists are
    expanded into individual metadata values.

    Example:
    ["Italian", "English"]

    becomes:

    Italian
    English
    """

    if value is None:
        return []

    if isinstance(value, list):
        return [
            str(item).strip()
            for item in value
            if str(item).strip()
        ]

    return [str(value).strip()]


# ==================================================
# UNIQUE VALUE COUNT
# ==================================================

def count_unique_values(series):
    """
    Count distinct metadata values.

    Lists are expanded before counting.

    Example:

    ["Italian", "English"]

    counts as two unique values,
    not as one combined string.
    """

    unique_values = set()

    for value in series:

        for item in flatten_metadata_value(value):
            unique_values.add(item)

    return len(unique_values)


# ==================================================
# METADATA REPORT GENERATION
# ==================================================

def generate_metadata_report(df):
    """
    Generate the bibliographic metadata report.

    Creates one row for every catalogue field containing:

    - field name
    - description
    - detected datatype
    - number of records
    - completed values
    - missing percentage
    - unique value count

    Used by the metadata dashboard.
    """

    metadata = []

    # Iterate through the central field dictionary.
    # This keeps the report synchronized with config.py.
    for internal_name, column_name in COLUMNS.items():

        # Ignore fields not present in the current catalogue.
        if column_name not in df.columns:
            continue

        series = df[column_name]

        total_records = len(series)

        # Count missing cells.
        missing = series.isna().sum()

        filled = total_records - missing

        missing_percentage = round(
            (missing / total_records) * 100,
            2
        )

        metadata.append(
            {
                "Field": column_name,

                "Description":
                    COLUMN_DESCRIPTIONS.get(
                        internal_name,
                        ""
                    ),

                "Data type":
                    analyse_value_type(series),

                "Records":
                    total_records,

                "Filled values":
                    filled,

                "Missing %":
                    missing_percentage,

                "Unique values":
                    count_unique_values(series)
            }
        )

    return pd.DataFrame(metadata)


# ==================================================
# METADATA DASHBOARD PAGE
# ==================================================

def show_metadata(report):
    """
    Display metadata analysis dashboard.

    Shows:
    - metadata table
    - missing values chart
    - datatype distribution
    """

    st.caption(
        "Analysis of bibliographic fields and data quality."
    )

    # Complete metadata report table.
    st.dataframe(
        report,
        use_container_width=True,
        height=700
    )

    st.divider()

    # ----------------------------------------------
    # Missing values analysis
    # ----------------------------------------------

    st.subheader(
        "Missing values overview"
    )

    missing_chart = (
        report[
            [
                "Field",
                "Missing %"
            ]
        ]
        .set_index("Field")
    )

    st.bar_chart(
        missing_chart
    )

    st.divider()

    # ----------------------------------------------
    # Datatype distribution
    # ----------------------------------------------

    st.subheader(
        "Field types"
    )

    type_count = (
        report["Data type"]
        .value_counts()
    )

    st.bar_chart(
        type_count
    )